# Generated by Django 2.0.1 on 2018-01-26 18:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(help_text='Número telefónico de contacto con el usuario', max_length=16, validators=[django.core.validators.RegexValidator('^\\+\\d{3}-\\d{3}-\\d{7}$', 'Número telefónico inválido. Solo se permiten números y los símbolos: + -')])),
                ('telefono_casa', models.CharField(help_text='Número telefónico de contacto con el usuario', max_length=16, validators=[django.core.validators.RegexValidator('^\\+\\d{3}-\\d{3}-\\d{7}$', 'Número telefónico inválido. Solo se permiten números y los símbolos: + -')])),
                ('ocupacion', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('user', models.OneToOneField(help_text='Relación entre los datos de registro y el usuario con acceso al sistema', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
