# Generated by Django 2.0.1 on 2018-01-15 20:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^[VE][\\d]{8}$', 'Introduzca un número de cédula válido. Solo se permiten números y una longitud de 8 carácteres. Se agrega un 0 si la longitud es de 7 carácteres.')])),
                ('telefono', models.CharField(help_text='Número telefónico de contacto con el usuario', max_length=15, validators=[django.core.validators.RegexValidator('^\\+\\d{2}-\\d{3}-\\d{7}$', 'Número telefónico inválido. Solo se permiten números y los símbolos: - +')])),
                ('correo', models.CharField(help_text='correo@correo.com', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
